"""initial schema

Revision ID: 582dcaddc1dd
Revises: 
Create Date: 2026-09-04 16:33:16.983565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582dcaddc1dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('email = lower(email)', name='ck_admin_users_email_lowercase'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index('ix_admin_users_email', ['email'], unique=True)

    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('learner_name', sa.String(length=120), nullable=True),
    sa.Column('grade_applying', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='contact', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.CheckConstraint("source IN ('contact', 'admissions')", name='ck_enquiries_source'),
    sa.CheckConstraint("status IN ('new', 'read', 'archived')", name='ck_enquiries_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.create_index('ix_enquiries_status_created', ['status', 'created_at'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('cover_image_url', sa.String(length=600), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at IS NULL OR ends_at >= starts_at', name='ck_events_end_after_start'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_published_start', ['is_published', 'starts_at'], unique=False)
        batch_op.create_index('ix_events_slug', ['slug'], unique=True)

    op.create_table('gallery_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_categories', schema=None) as batch_op:
        batch_op.create_index('ix_gallery_categories_slug', ['slug'], unique=True)

    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('excerpt', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('cover_image_url', sa.String(length=600), nullable=True),
    sa.Column('cover_image_alt', sa.String(length=300), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index('ix_news_articles_category', ['category'], unique=False)
        batch_op.create_index('ix_news_articles_published', ['is_published', 'published_at'], unique=False)
        batch_op.create_index('ix_news_articles_slug', ['slug'], unique=True)

    op.create_table('rate_limit_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=60), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limit_hits', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_hits_lookup', ['bucket', 'identifier', 'created_at'], unique=False)

    op.create_table('site_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.Column('value_type', sa.String(length=16), server_default='string', nullable=False),
    sa.Column('group', sa.String(length=40), server_default='general', nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("value_type IN ('string', 'text', 'number', 'url', 'bool', 'json')", name='ck_site_settings_value_type'),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.create_index('ix_site_settings_group', ['group'], unique=False)

    op.create_table('gallery_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('alt_text', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('thumb_url', sa.String(length=600), nullable=True),
    sa.Column('storage_key', sa.String(length=200), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['gallery_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_images', schema=None) as batch_op:
        batch_op.create_index('ix_gallery_images_category_position', ['category_id', 'position'], unique=False)
        batch_op.create_index('ix_gallery_images_featured', ['is_featured'], unique=False)

    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_type', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index('ix_token_blocklist_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_token_blocklist_jti', ['jti'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index('ix_token_blocklist_jti')
        batch_op.drop_index('ix_token_blocklist_expires')

    op.drop_table('token_blocklist')
    with op.batch_alter_table('gallery_images', schema=None) as batch_op:
        batch_op.drop_index('ix_gallery_images_featured')
        batch_op.drop_index('ix_gallery_images_category_position')

    op.drop_table('gallery_images')
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_index('ix_site_settings_group')

    op.drop_table('site_settings')
    with op.batch_alter_table('rate_limit_hits', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_hits_lookup')

    op.drop_table('rate_limit_hits')
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index('ix_news_articles_slug')
        batch_op.drop_index('ix_news_articles_published')
        batch_op.drop_index('ix_news_articles_category')

    op.drop_table('news_articles')
    with op.batch_alter_table('gallery_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_gallery_categories_slug')

    op.drop_table('gallery_categories')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_slug')
        batch_op.drop_index('ix_events_published_start')

    op.drop_table('events')
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.drop_index('ix_enquiries_status_created')

    op.drop_table('enquiries')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_users_email')

    op.drop_table('admin_users')
    # ### end Alembic commands ###
